apply plugin: 'jacoco'
jacoco {
    toolVersion = '0.8.11'
}

tasks.withType(Test).configureEach {
    jacoco.includeNoLocationClasses = true
    jacoco.excludes = ["jdk.internal.*"]
}
tasks.register('coverageReport', JacocoReport) {
    dependsOn = ['testDebugUnitTest']
    group = "Reporting"
    description = "Generate Coverage by jacoco"
    reports {
        html.required = true
    }
    def excludesClasses = ['**/databinding/*Binding*.*',
                           '**/R.class',
                           '**/R$*.class',
                           '**/BuildConfig.*',
                           '**/Manifest*.*',
                           '**/*Test*.*',
                           'android/**/*.*',
                           // butterKnife
                           '**/*$ViewInjector*.*',
                           '**/*$ViewBinder*.*',
                           '**/Lambda$*.class',
                           '**/Lambda.class',
                           '**/*Lambda.class',
                           '**/*Lambda*.class',
                           '**/*_MembersInjector.class',
                           '**/Dagger*Component*.*',
                           '**/*Module_*Factory.class',
                           '**/di/module/*',
                           '**/*_Factory*.*',
                           '**/*Module*.*',
                           '**/*Dagger*.*',
                           '**/*Hilt*.*',
                           // kotlin
                           '**/*MapperImpl*.*',
                           '**/*$ViewInjector*.*',
                           '**/*$ViewBinder*.*',
                           '**/BuildConfig.*',
                           '**/*Component*.*',
                           '**/*BR*.*',
                           '**/Manifest*.*',
                           '**/*$Lambda$*.*',
                           '**/*Companion*.*',
                           '**/*Module*.*',
                           '**/*Dagger*.*',
                           '**/*Hilt*.*',
                           '**/*MembersInjector*.*',
                           '**/*_MembersInjector.class',
                           '**/*_Factory*.*',
                           '**/*_Provide*Factory*.*',
                           '**/*Extensions*.*']
    classDirectories.from = files([fileTree(dir: "${layout.buildDirectory}/tmp/kotlin-classes/debug", excludes: excludesClasses),])
    def coverageSourceDirectory = ["${project.projectDir}\\src\\main\\kotlin"]
    additionalClassDirs.from(files(coverageSourceDirectory))
    sourceDirectories.from = file(coverageSourceDirectory)
    getExecutionData().from(fileTree(dir: project.projectDir, includes: ['**/*.exec', '**/*.ec']))
    doLast {
        def m = new File("${project.layout.buildDirectory}/reports/jacoco/${testTaskName}Coverage/html/index.html")
                .text =~ /Total[^%]*>(\d?\d?\d?%)/
        if (m) {
            println "Test coverage: ${m[0][1]}"
        }
        println "Coverage report path -> file://${reports.html.entryPoint}"
    }
}