name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  lint:
    name: Android Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle
      - run: ./gradlew lint --stacktrace --warning-mode=all
      - uses: yutailang0119/action-android-lint@v3
        with:
          report-path: build/reports/*.html # Support glob patterns by https://www.npmjs.com/package/@actions/glob
        continue-on-error: false # If annotations contain error of severity, action-android-lint exit 1.
      - name: Upload lint report
        uses: actions/upload-artifact@v3
        with:
          name: LintReport.html
          path: app/build/reports/lint-results-debug.html

  build:
    name: Build
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build --stacktrace --warning-mode=all

  test:
    name: Test coverage
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle
      - name: test with Gradle
        run: ./gradlew testDebugUnitTestCoverageVerification --stacktrace --warning-mode=all
      - name: Upload jacoco report
        uses: actions/upload-artifact@v3
        with:
          name: JacocoReport.html
          path: app/build/reports/jacoco/testDebugUnitTestCoverage/html/index.html
  apk:
    name: Debug apk
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle
      - name: build APK
        run: ./gradlew assembleDebug --stacktrace
      - name: Upload APK debug
        uses: actions/upload-artifact@v3
        with:
          name: Pokedex.apk
          path: app/build/outputs/apk/debug/app-debug.apk