name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  lint:
    name: Android Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
#        with:
#          fetch-depth: 1
      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle
      - run: ./gradlew lint --stacktrace
      - uses: yutailang0119/action-android-lint@v3
        with:
          report-path: build/reports/*.html # Support glob patterns by https://www.npmjs.com/package/@actions/glob
        continue-on-error: false # If annotations contain error of severity, action-android-lint exit 1.

  build:
    name: Build
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build --stacktrace
  test:
    name: Tests
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle
      - name: test with Gradle
        run: ./gradlew app:testDevDebugUnitTestCoverageVerification --stacktrace
  apk:
    name: Debug apk
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle
      - name: build APK
        run: ./gradlew assembleDebug --stacktrace
      - name: upload APK
        uses: actions/upload-artifact@v3
        with:
          name: pokedex
          path: app/build/outputs/apk/debug/app-debug.apk