name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  lint:
    name: Android Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@latest
      - name: Setup JDK 17
        uses: actions/setup-java@latest
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle
      - run: ./gradlew lint --stacktrace --warning-mode=all
      - uses: yutailang0119/action-android-lint@lastest
        with:
          report-path: build/reports/*.html # Support glob patterns by https://www.npmjs.com/package/@actions/glob
        continue-on-error: false # If annotations contain error of severity, action-android-lint exit 1.
      - name: Upload lint report
        uses: actions/upload-artifact@lastest
        with:
          name: LintReport
          path: app/build/reports/lint-results-debug.html
  build:
    name: Build
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@latest
      - name: Setup JDK 17
        uses: actions/setup-java@latest
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build --stacktrace --warning-mode=all
  test:
    name: Test coverage
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@latest
      - name: set up JDK 17
        uses: actions/setup-java@latest
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle
      - name: test with Gradle
        run: ./gradlew testDebugUnitTestCoverageVerification --stacktrace --warning-mode=all
      - name: Upload jacoco report
        uses: actions/upload-artifact@latest
        with:
          name: JacocoReport
          path: app/build/reports/jacoco/testDebugUnitTestCoverage/html/
  apk:
    name: Debug
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@latest
      - name: Setup JDK 17
        uses: actions/setup-java@latest
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle
      - name: build APK
        run: ./gradlew clean assembleDebug --stacktrace
      - name: Upload APK debug
        uses: actions/upload-artifact@latest
        with:
          name: Pokedex
          path: app/build/outputs/apk/debug/app-debug.apk
  release:
    name: Release
    needs: apk
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download APK from build
        uses: actions/download-artifact@latest
        with:
          name: Pokedex
      - name: Create Release
        id: create_release
        uses: ncipollo/release-action@latest
        with:
          artifacts: "Pokedex/app-debug.apk"
      - name: Upload Release APK
        id: upload_release_asset
        uses: actions/upload-release-asset@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: Pokedex/app-debug.apk
          asset_name: Pokedex.apk
          asset_content_type: application/zip